--- !ditz.rubyforge.org,2008-03-06/project 
name: ffi-ncurses
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: ffi-ncurses
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: mac
- !ditz.rubyforge.org,2008-03-06/component 
  name: linux
- !ditz.rubyforge.org,2008-03-06/component 
  name: docs
- !ditz.rubyforge.org,2008-03-06/component 
  name: jruby
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-02-15 14:45:23.949378 Z
    - Sean O'Halpin <sean.ohalpin@gmail.com>
    - created
    - first gem version
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.3.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-02-15 14:46:52.716797 Z
    - Sean O'Halpin <sean.ohalpin@gmail.com>
    - created
    - update to use JRuby 1.1.7 features
